version: '3.8'

services:
  currency-api:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: currency-microservice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379  # ✅ Internal network connection
      - TOKEN=${TOKEN}
      - API_URL=${API_URL:-https://eproxy.moneeflo.com/}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - currency-internal  # ✅ Internal network for fast communication
    labels:
      - "dockploy.enable=true"
      - "dockploy.port=3000"

  redis:
    image: redis:7-alpine
    container_name: currency-redis
    restart: unless-stopped
    command: |
      redis-server 
      --appendonly yes 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --save 60 1000
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # ✅ Custom Redis config
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - currency-internal  # ✅ Same internal network
    sysctls:
      - net.core.somaxconn=1024
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# ✅ Internal network for ultra-fast communication
networks:
  currency-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis_data:
    driver: local
